# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  auth0_domain: <%= ENV['AUTH0_NAMESPACE'] %>
  auth0_id: <%= ENV['AUTH0_CLIENT_ID'] %>
  auth0_secret: <%= ENV['AUTH0_CLIENT_SECRET'] %>

#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7c1ee5f8c0eff4233b626c4e8060b4fc7e340f0f1d5ffe51c059cfb1674287e2cb466089b85abac27bdeb79acaf95f59335eb07e2089f3a33b8d372de1700710

test:
  secret_key_base: 4625eb538ff47bc984d72f7879b5476e241417cd0594ae0a7a1d924398b3b1c3dbd95ca6fca77ca91f8826d9c270774ae91214f71dc5256c42602f45a881ee82

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
